### ISSUE TITLE
二阶堂角色图片无法替换

### ISSUE THREAD

**Issue by shp241** [MajsoulPlus/majsoul-plus-client#11]
一姬和相原还有千织都可以唯独二阶堂替换不了
图片放在了files\0\v0.4.1.w\extendRes\charactor\erjietang
json文件如下
{
      "from": "/0/[^/]+/extendRes/charactor/erjietang\\.png",
        "to": "/0/v0.4.1.w/extendRes/charactor/erjietang\\.png"
},
已重新加载过

**Comment by iamapig120** [comment]
以下是一个 mod.json 示范
您可以参考这个来实现您自己的二阶堂Mod

{
  "name": "二阶堂普通立绘反和谐",
  "author": "Handle",
  "description": "反和谐立绘来源于老版本雀魂",
  "replace": [
    {
      "from": "/0/[^/]+/extendRes/charactor/erjietang/([^/]+)\\.png",
      "to": "/0/v0.4.1.w/extendRes/charactor/erjietang/$1.png"
    }
  ]
}
