### ISSUE TITLE
[BUG] 启动时窗口消失并留有后台不能自动关闭

### ISSUE THREAD

**Issue by zsguy** [MajsoulPlus/majsoul-plus-client#12]
**Bug 描述**
在我这边会在刚启动加载时窗口消失(没加载入大厅之前),后台留有进程,占用30-50%的cpu占用,得要手动关闭进程,很容易复现
使用的mod是nga找到的替换bgm为海猫的mod和自带替换壁纸自己更换了一个,不知道有没有错误日志能反馈给你
在公司和家里电脑都是这样,win10 64bit,早上测试32位程序和64位都有如此情况

**Comment by zsguy** [comment]
https://pan.baidu.com/s/1xt8OFDXWScLGsVrzMbjzxA   tmgp

**Comment by zsguy** [comment]
附上mod地址供测试,但是我把mod都关闭了依旧会窗口消失

**Comment by iamapig120** [comment]
已复现，正在尝试寻找问题

**Comment by iamapig120** [comment]
似乎是出现在高版本Electron release中的问题，正尝试使用低版本编译

**Comment by iamapig120** [comment]
尴尬……又复现不了了……下次再遇到就再看看什么情况

**Comment by zsguy** [comment]
中午午休无聊又想了办法,把存在appdata的本地数据文件夹删了重新登陆,连续几次都正常了,看来可能是版本升级新旧数据冲突有关,又可以摸鱼了哈哈哈哈哈

**Comment by iamapig120** [comment]
0KB 那个我也不清楚为什么会生成，捂脸，似乎是Log文件什么的，然后可以确认是新版本Electron的锅，晚一些发布降级版本

**Comment by iamapig120** [comment]
fixed https://github.com/MajsoulPlus/majsoul-plus-client/releases/tag/v1.5.8
