### ISSUE TITLE
[BUG] 最大化出现滚动条（窗口与游戏界面大小不符）

### ISSUE THREAD

**Issue by inkuxuan** [MajsoulPlus/majsoul-plus-client#14]
**Bug 描述**
窗口最大化时，游戏界面会超出窗口范围，导致出现滚动条；
任务栏左置时出现竖直和水平滚动条、任务栏下置时出现竖直滚动条
使用F11全屏时则无此问题

**相关信息**
笔记本，分辨率为1920*1080，Windows显示设置（高级缩放设置）缩放比例为125%

**截图**
[问题截图1](https://i.loli.net/2019/01/18/5c41939b0cd04.png)
[问题截图2](https://i.loli.net/2019/01/18/5c41951445c47.png)
[Windows缩放设置](https://i.loli.net/2019/01/18/5c41947c29cb8.png)

**客户端信息:**
 - 操作系统: [Windows 10 1809及1803]
 - 系统架构 [x64]
 - 版本号 [1.6.1 Beta-1 及 1.6.1]

**备注**
使用Google Chrome、FireFox访问官方游戏页不会出现类似问题

**Comment by iamapig120** [comment]
收到，稍晚些会尝试复现

**Comment by iamapig120** [comment]
成功复现，这个bug同样出现在官方版本内，
已知问题为在特定分辨率下，由于页面缩放，导致雀魂的Canvas缩放不正确引发问题

**Comment by iamapig120** [comment]
Fixed https://github.com/MajsoulPlus/majsoul-plus-client/releases/tag/v1.8.8
