### ISSUE TITLE
无法在mac os上运行

### ISSUE THREAD

**Issue by jerryzmtz** [MajsoulPlus/majsoul-plus-client#15]
确实无法在macOS下运行。没有任何错误提示。可以启动程序，但是点击【启动游戏】以后没有反应

**Comment by iamapig120** [comment]
您好，已收到，请问方便下载 1.7.2 再次尝试下么
https://github.com/MajsoulPlus/majsoul-plus-client/releases/tag/v1.7.2

**Comment by hyunrealshadow** [comment]
@jerryzmtz 请移动到应用程序下运行
Please move it to the Application folder and run it again

**Comment by jerryzmtz** [comment]
已經修復了，謝謝！
