### ISSUE TITLE
[BUG] 第三方登陆（QQ）无法加载插件和模组

### ISSUE THREAD

**Issue by luoguoqing250** [MajsoulPlus/majsoul-plus-client#16]
**Bug 描述**
登陆账号时使用QQ登陆无法加载模组和插件

**如何重现**
以下为重现步骤：
1. 打开雀魂plus
2. 勾选插件/模组
3. 开始游戏
4. 登陆账号选择QQ登陆
5.插件和模组无效

截图
![image](https://user-images.githubusercontent.com/46950982/51585491-87395800-1f14-11e9-9ea8-51c5caa0d55f.png)
![image](https://user-images.githubusercontent.com/46950982/51585502-8b657580-1f14-11e9-9bd4-f44796e64c14.png)

使用模组/插件

**客户端信息 (请完善以下信息):**
 - 操作系统: [win10 /win7] 一个朋友是win7 也有这个bug
 - 系统架构 [x64]
 - 版本号 [v1.8.3]

**Comment by iamapig120** [comment]
感谢反馈，已修复
