### ISSUE TITLE
点击exe文件没有反应

### ISSUE THREAD

**Issue by frigee** [MajsoulPlus/majsoul-plus-client#17]
win7 64位系统 杀软已关
点击exe文件后，指针会显示一小下沙漏图标，然后就无事发生了

**Comment by frigee** [comment]
我试了好几个版本，包括最新的1-8-9和1-8-5

**Comment by iamapig120** [comment]
> 我试了好几个版本，包括最新的1-8-9和1-8-5

请问您方便提供什么联系方式么……我这边没法复现……

**Comment by frigee** [comment]
联系我的qq吧136152190

**Comment by iamapig120** [comment]
无法确保非原版系统的可用性，以及Windows7的可用性，建议升级您的计算机
