### ISSUE TITLE
[feature request] 在设置中加入 清空资源缓存 和 清空游戏缓存 功能

### ISSUE THREAD

**Issue by iamapig120** [MajsoulPlus/majsoul-plus-client#27]
**您是在使用中遇到了什么问题导致的您提交功能建议么？如果是，请描述您遇到的问题**
在设置中加入 清空资源缓存 和 清空游戏缓存 功能

**描述您希望的解决方案**
一段清晰且简练的描述说明您希望发生的操作和反馈

**描述您希望的备选方案**
对您考虑过的任何替代解决方案或功能的清晰而简明的描述

**备注**
在此处添加有关功能请求的任何其他说明或屏幕截图

**Comment by molingyu** [comment]
建议重构一下setting页面 将类型和value分离而不是依赖
