### ISSUE TITLE
在窗口切换的时候可能会黑屏

### ISSUE THREAD

**Issue by luciouskami** [MajsoulPlus/majsoul-plus-client#7]
随机黑屏，也不固定，网页版本的的雀魂也有这个问题，谷歌内核的浏览器频发。不知道有解吗？
已经可以确认是雀魂本身的问题。在官方安卓客户端上测试0黑屏，猜测可能是渲染引擎的问题，可以尝试换个渲染引擎。

**Comment by luciouskami** [comment]
大概看了一下，果然是雀魂本身的代码不完善的问题。对部分可能导致重绘的操作没有回调，这就导致了重绘事件发生了调用的是系统的缺省函数，然后就黑屏了，看起来像是黑屏了一样。

**Comment by iamapig120** [comment]
渲染引擎的话，Electron使用的是Chromium内核……暂时无法更换……
只是纯粹的黑屏的话……或许可以按照雀魂官网上的联系方式和官方联系一下……

**Comment by luciouskami** [comment]
> 渲染引擎的话，Electron使用的是Chromium内核……暂时无法更换……对
> 只是纯粹的黑屏的话……或许可以按照雀魂官网上的联系方式和官方联系一下……

果然是Chromium的问题，这在chrome最近的已知问题中也有提到，等下可以尝试把代码用moniblink跑一下，它是Chromium49，可能不会崩溃。

**Comment by luciouskami** [comment]
@iamapig120 使用miniblink的话并不会出现黑屏问题，可能是新版Chromium（Chrome）向下兼容出了问题。可以尝试提供一个基于miniblink的版本。

**Comment by iamapig120** [comment]
> @iamapig120 使用miniblink的话并不会出现黑屏问题，可能是新版Chromium（Chrome）向下兼容出了问题。可以尝试提供一个基于miniblink的版本。

这个项目是基于Electron实现的……Electron本身又是使用了Chromium69……

**Comment by luciouskami** [comment]
> > @iamapig120 使用miniblink的话并不会出现黑屏问题，可能是新版Chromium（Chrome）向下兼容出了问题。可以尝试提供一个基于miniblink的版本。
> 
> 这个项目是基于Electron实现的……Electron本身又是使用了Chromium69……

只有win10 1607 and lower会出现这个问题 。
won10 1703 and upper 以及 win8 /win8.1 win7 sp1不会出现这个问题

**Comment by iamapig120** [comment]
说起来我Win10 1809也偶发黑屏……迷……而且如果是跨域的话，客户端是完全允许跨域的啊……

**Comment by luciouskami** [comment]
官方没有给出有用的答复，目前网页版本的临时解决方法是关闭硬件加速。

**Comment by luciouskami** [comment]
@iiamapig120 经过测试，发现在不关闭GPU加速的情况下，在N卡驱动中单独添加Chrome和客户端，指定它们使用独立显卡（高性能处理器）以后，连打3把南风场没有再出现黑屏效果。问题越发扑朔迷离了起来~~~

**Comment by iamapig120** [comment]
> @iamapig120 经过测试，发现在不关闭GPU加速的情况下，在N卡驱动中单独添加Chrome和客户端，指定它们使用独立显卡（高性能处理器）以后，连打3把南风场没有再出现黑屏效果。问题越发扑朔迷离了起来~~~

我屏蔽了核显，实话实说我还真没遇到过黑屏…………

**Comment by luciouskami** [comment]
> > @iamapig120 经过测试，发现在不关闭GPU加速的情况下，在N卡驱动中单独添加Chrome和客户端，指定它们使用独立显卡（高性能处理器）以后，连打3把南风场没有再出现黑屏效果。问题越发扑朔迷离了起来~~~
> 
> 我屏蔽了核显，实话实说我还真没遇到过黑屏…………

按照一般情况来说，使用核显还是独显应由驱动程序或者应用程序自动控制，用户不需要干预这个判断，但是实际操作来说必须要用户强制指定GPU，黑屏现在无外乎两种情况：1、N卡驱动问题，核显显存不足，没有自动切换独显；2雀魂代码问题，没有指定GPU；3谷歌Render问题。

**Comment by iamapig120** [comment]
我觉得应该不会是雀魂没指定GPU的原因，网页游戏做不到这些
然后很可能是N卡默认浏览器之类应用核显的原因……我猜

**Comment by luciouskami** [comment]
> 我觉得应该不会是雀魂没指定GPU的原因，网页游戏做不到这些
> 然后很可能是N卡默认浏览器之类应用核显的原因……我猜

啊，是的。因为我是做端游的，首先就会想到渲染引擎。然后雀魂是用webgl的，webgl不知道有没有类似的接口，我感觉应该会有吧。

**Comment by iamapig120** [comment]
提供了新的接口，可以控制开启或关闭硬件加速（configs-user.json）
未来版本会加入可视化设置页面

**Comment by luciouskami** [comment]
> 提供了新的接口，可以控制开启或关闭硬件加速（configs-user.json）
> 未来版本会加入可视化设置页面

暂时只能这样处理了，不过关闭gpu加速以后画面可能会有很强的拖拽感。

**Comment by WcLyic** [comment]
建议尝试: 滚动网页/网页缩放刷新下 viewport , 或者将包含Canvas的Div隐藏再显示 能否恢复正常

**Comment by luciouskami** [comment]
> 建议尝试: 滚动网页/网页缩放刷新下 viewport , 或者将包含Canvas的Div隐藏再显示 能否恢复正常

这个我在第一次提的时候就说清楚了，雀魂并没有对这些可能触发重绘的消息作响应，导致了调用的是默认的重绘函数而不是webGL的所以导致黑屏。
